### ISSUE TITLE
Last visited folder bookmark

### ISSUE THREAD

**Issue by Stefanomarton** [dedukun/bookmarks.yazi#10]
Hi there,
I love your plugin, these are a set of features that was really missing in yazi.

I would like to know if there is some easy way to implement the same behaviour in ranger. In ranger there's always available (as in vim) the `' '` bookmark that move you to the last visited folder

![image](https://github.com/dedukun/bookmarks.yazi/assets/80684231/75759c77-3d56-4fba-8e19-484842ad87ee)

Do you think is possible to create the same behaviour? If you have any idea I could try to implement it

**Comment by sxyazi** [comment]
If I'm getting it right, it seems like it's what the [back](https://yazi-rs.github.io/docs/configuration/keymap#manager.back) and [forward](https://yazi-rs.github.io/docs/configuration/keymap#manager.forward) command do?

**Comment by Stefanomarton** [comment]
> If I'm getting it right, it seems like it's what the [back](https://yazi-rs.github.io/docs/configuration/keymap#manager.back) and [forward](https://yazi-rs.github.io/docs/configuration/keymap#manager.forward) command do?

It is kind of more complex.
For example:

- I open yazi in folder A
-  enter B and C folder (without scrolling in files in to folder). 
- Then I enter folder D and scroll up and down in the files. 
- I cd in to home using `gh`. 

The bookmark `''` would be binded to D

`''` bookmark automatically bind to the last folder you've done something other than moving across.

**Comment by dedukun** [comment]
Hey,

It would be easy if `''` mapped to the last bookmark that you used, but the way that you described is a bit complicated, I'm not sure how it can be done at the moment.

I'll have a look into it and come back to you.

**Comment by Stefanomarton** [comment]
> Hey,
> 
> It would be easy if `''` mapped to the last bookmark that you used, but the way that you described is a bit complicated, I'm not sure how it can be done at the moment.
> 
> I'll have a look into it and come back to you.

This is the .py file releated to bookmark in ranger, idk if can be useful [(here)](https://github.com/ranger/ranger/blob/master/ranger/container/bookmarks.py)

**Comment by dedukun** [comment]
Hey @Stefanomarton 

I've made a new PR #11 which implements this feature, however at the moment it has a bug where we are assuming that the directory where Yazi is opened is the home directory.
This only matters in the case that a user opens Yazi, immediately uses a jump like `gh` and then tries to go back with `''` . 

This will be fixed in a couple days, I'm waiting for some new features in Yazi to be able to do that, however in the meantime you can use the PR, if you find anything wrong with the current implementation please let me know.

To enable it make sure to run the plugin's `setup` function in Yazi's `init.lua`, i.e. `~/.config/yazi/init.lua` like:

```lua
require("bookmarks"):setup({ save_last_directory = true })
```

**Comment by Stefanomarton** [comment]
Tested against cargo git version (Yazi 0.2.4 (b51babd 2024-04-01),  working nicely

Thanks !!

**Comment by dedukun** [comment]
The latest commit in Yazi https://github.com/sxyazi/yazi/commit/b51babde1c9f26d95e4fc383a36eb78498c23809 fixes the bug that I mentioned above (thanks for the quick response @sxyazi :smile:)

**Comment by dedukun** [comment]
@Stefanomarton Do you want to have it the same as in ranger? 
We can use the `save_last_directory`  flag to indicate if we want the current behavior and rangers behavior.

From what you are describing for rangers behavior I just need to not subscribe to the `cd` event that I'm using at the moment.

**Comment by Stefanomarton** [comment]
> We can use the `save_last_directory` flag to indicate if we want the current behavior and rangers behavior.
> 
> From what you are describing for rangers behavior I just need to not subscribe to the `cd` event that I'm using at the moment.

Yes it work as expected and it's nice.

Thanks !

**Comment by VimalMollyn** [comment]
Hi, thanks for adding this feature! I noticed that the last visited folder bookmark does not get saved between yazi sessions. How could I add that functionality?

**Comment by dedukun** [comment]
It's not supported at the moment, but it's a feature that I can add to the plugin, I will do it in the next couple of days.

Also, could you create a new issue to track this requested? It's easier for me to track any development in a dedicated issue than in this one that is already closed.
