### ISSUE TITLE
Does not require the latest main branch anymore

### ISSUE THREAD

**Issue by raffaem** [dedukun/bookmarks.yazi#15]
It's working for me with yazi 0.2.5, so it seems it doesn't require the last main branch anymore

**Comment by dedukun** [comment]
Hey,

Yes you are right, however the plugin API is still pretty new and in beta, so there may be some change later in the API that might introduce a issue, I think that I'll wait for it to get out of beta to change the README.

There's also a [plugin manager being implemented](https://github.com/sxyazi/yazi/pull/985), I might also change it then.

**Comment by dedukun** [comment]
Well I thought about it better and I might as well change the README now (done in this [commit](https://github.com/dedukun/bookmarks.yazi/commit/3907dd910bf26597e8f2bab449df2d83a0ad6bd9), I'll update it later if there's any breaking change in the future.

Thanks for raising the issue
