### ISSUE TITLE
Persistency doesnt work for me, "ya" not set

### ISSUE THREAD

**Issue by danscheer** [dedukun/bookmarks.yazi#18]
I followed the installation proecesses (yazi 0.2.5). Besides that "ya" for the package manager doesnt exist in a normal yazi installation for the package manager command (maybe you set an alias that i dont know of), ya seems also to be used inside of the plugins init.lua, and maybe therefore the persistence feature set in the yazi/init.lua doesnt work?

**Comment by dedukun** [comment]
Hey,

The `ya` command doesn't exist in 0.2.5, at the moment you need to install the latest commit of yazi if you want to use it, [if you use cargo you need to install both `yazi-fm` as well as `yazi-cli`](https://yazi-rs.github.io/docs/installation#cargo).

If you have the plugin installed manually, you should just need to run the `setup` function in `yazi/init.lua` with the desired persistency mode, aka `all` or `vim`. Does the plugin work correctly besides the persistency?

**Comment by danischeer** [comment]
Thanks for reply. 

> The `ya` command doesn't exist in 0.2.5, at the moment you need to install the latest commit of yazi if you want to use it, [if you use cargo you need to install both `yazi-fm` as well as `yazi-cli`](https://yazi-rs.github.io/docs/installation#cargo).

Thanks for the clarification!
 
> If you have the plugin installed manually, you should just need to run the `setup` function in `yazi/init.lua` with the desired persistency mode, aka `all` or `vim`. Does the plugin work correctly besides the persistency?

Yes, besides the persistency everything works. Dont know if i have to activate something for the DDS, maybe there i the Problem. I switched to Yet Another Bookmark plugin, it works with persistency, but i would like to use your plugin for ease of use.

**Comment by dedukun** [comment]
Ok, can you send some debug information? It would be helpful to get the following:

- `yazi --debug`
- the `bookmarks.setup` function that you are using in `yazi/init.lua` (if you don't mind you can just put the full `yazi/init.lua` file)
- the output of `~/.local/state/yazi/yazi.log` when you create a bookmark

And this is just to make sure, but you are in the latest commit of the plugin right?

**Comment by AnirudhG07** [comment]
I am also facing this issue, I am using v0.2.5 on macOS, and I would like to use "vim" mode for persistency, but when I do it, it creates a process and shows "99% 1 left" (in red color), but doesnt completes the process.

**Comment by dedukun** [comment]
You must have updated the plugin with my commit from a couple of days ago right? 

Upstream changed how DDS works a couple of days ago, seeing that you are in yazi v0.2.5 please checkout the plugin to the tag [`0.2.5`](https://github.com/dedukun/bookmarks.yazi/tree/0.2.5), you were probably having a different issue before.

If you could do that and then resend the yazi.log again it would be very helpful.

You config looks correct, so I don't think that it has anything to do with that. The only thing that I see is that you are using the `vim` persist method, so only upper case letters are saved to persistent memory.

**Comment by Urie96** [comment]
Same problem. Finally solved by `rm ~/.local/state/yazi/.dds`

**Comment by AnirudhG07** [comment]
> You must have updated the plugin with my commit from a couple of days ago right?
> 
> Upstream changed how DDS works a couple of days ago, seeing that you are in yazi v0.2.5 please checkout the plugin to the tag [`0.2.5`](https://github.com/dedukun/bookmarks.yazi/tree/0.2.5), you were probably having a different issue before.
> 
> If you could do that and then resend the yazi.log again it would be very helpful.
> 
> You config looks correct, so I don't think that it has anything to do with that. The only thing that I see is that you are using the `vim` persist method, so only upper case letters are saved to persistent memory.

```
2024-06-28T08:10:22.932115Z ERROR yazi::lives::lives: Kind must be alphanumeric with dashes
stack traceback:
	[C]: in field 'pub_to'
	[string "yazi-plugin/src/loader/loader.rs:66:28"]:88: in function <[string "yazi-plugin/src/loader/loader.rs:66:28"]:68>
	>[C]: in upvalue '_save_state'
	[string "yazi-plugin/src/loader/loader.rs:66:28"]:130: in function <[string "yazi-plugin/src/loader/loader.rs:66:28"]:113>

    at yazi-fm/src/lives/lives.rs:68
```

I deleted and redownloaded ur plugin. Here is the log

**Comment by dedukun** [comment]
> > You must have updated the plugin with my commit from a couple of days ago right?
> > Upstream changed how DDS works a couple of days ago, seeing that you are in yazi v0.2.5 please checkout the plugin to the tag [`0.2.5`](https://github.com/dedukun/bookmarks.yazi/tree/0.2.5), you were probably having a different issue before.
> > If you could do that and then resend the yazi.log again it would be very helpful.
> > You config looks correct, so I don't think that it has anything to do with that. The only thing that I see is that you are using the `vim` persist method, so only upper case letters are saved to persistent memory.
> 
> ```
> 2024-06-28T08:10:22.932115Z ERROR yazi::lives::lives: Kind must be alphanumeric with dashes
> stack traceback:
> 	[C]: in field 'pub_to'
> 	[string "yazi-plugin/src/loader/loader.rs:66:28"]:88: in function <[string "yazi-plugin/src/loader/loader.rs:66:28"]:68>
> 	>[C]: in upvalue '_save_state'
> 	[string "yazi-plugin/src/loader/loader.rs:66:28"]:130: in function <[string "yazi-plugin/src/loader/loader.rs:66:28"]:113>
> 
>     at yazi-fm/src/lives/lives.rs:68
> ```
> 
> I deleted and redownloaded ur plugin. Here is the log. the vim mode seems more useful to me than all

@AnirudhG07  Can you `git checkout yazi-0.2.5` in the plugin folder and try again. (You might also need to fetch the branch) 

That seems to be the same issue as before, which is because I had to update the plugin to support upstream Yazi, so you should be in branch `[yazi-0.2.5](https://github.com/dedukun/bookmarks.yazi/tree/yazi-0.2.5)` of this plugin for it to work.
