### ISSUE TITLE
Persistence `all` doesn't work

### ISSUE THREAD

**Issue by wojciech-kulik** [dedukun/bookmarks.yazi#21]
Hi, 

I'm using kitty terminal on macOS. When I close & reopen yazi, the bookmarks are not available anymore.

My config:
```lua
require("bookmarks"):setup({
	save_last_directory = false,
	persist = "all",
	desc_format = "full",
	notify = {
		enable = true,
		timeout = 2,
		message = {
			new = "New bookmark '<key>' -> '<folder>'",
			delete = "Deleted bookmark in '<key>'",
			delete_all = "Deleted all bookmarks",
		},
	},
})
```

**Comment by wojciech-kulik** [comment]
O_O it suddenly started working even though I didn't change anything :D

**Comment by dedukun** [comment]
Hey,

Mh I did some tests to see if something broke with some update but it's sill working for me, so I'm not sure what happened there. 
I'll close the issue for now but let me know if it happens again and I'll reopen it and investigate further.

**Comment by panda7789** [comment]
@dedukun Hi i have same issue on Windows. When on same session bookmarks works great, but when i close yazi, all bookmarks are gone.
In other issue there was something about deleting .dds file.
I deleted it but it wont be recreated again as i supposted.

**Comment by dedukun** [comment]
@panda7789 Did you have only 1 Yazi instance running? If yes can you check if the same issue persists if you have multiple instances running?

**Comment by ZRabadaber** [comment]
still not work under windows. I tryed delete file dds, no changes.

yazi --debug output:

```
Yazi
    Version: 0.3.0 (7a380c2 2024-08-01)
    Debug  : false
    OS     : windows-x86_64 (windows)

Ya
    Version: 0.3.0

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : WezTerm

Adapter
    Adapter.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY : None
    DISPLAY         : None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : None
    EDITOR             : None
    YAZI_FILE_ONE      : Some("C:\\Program Files\\Git\\usr\\bin\\file.exe")
    YAZI_CONFIG_HOME   : Some("C:\\Users\\zraba\\AppData\\Roaming\\yazi\\config")
    ZELLIJ_SESSION_NAME: None

Text Opener
    default: Some(Opener { run: "hx \"%*\"", block: true, orphan: false, desc: "Helix", for_: None, spread: true })
    block  : Some(Opener { run: "hx \"%*\"", block: true, orphan: false, desc: "Helix", for_: None, spread: true })

tmux
    TMUX   : false
    Version: program not found

Dependencies
    file             : 5.45
    ueberzugpp       : program not found
    ffmpegthumbnailer: program not found
    magick           : program not found
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : program not found
    chafa            : program not found
    zoxide           : 0.9.4
    7z               : 24.07
    7zz              : program not found
    jq               : 1.7.1

--------------------------------------------------
```

**Comment by dedukun** [comment]
@ZRabadaber Has with above, did you have only 1 instance of Yazi running, or multiple? If you only had 1 can you test with at least two instances of Yazi running?

**Comment by ZRabadaber** [comment]
@dedukun yes. if I have two instances of Yazi, all work fine. on my ubuntu 24.04 same problem. two instances of Yazi work fine

**Comment by dedukun** [comment]
Yeah I'll have better a look at it during the weekend, but I think this is a issue with the DDS implementation in Yazi itself.

**Comment by debajit** [comment]
+1. I am seeing the same issue. I have only one instance of yazi running.

**Comment by eyck-dev** [comment]
also facing same issue when having one instance while bookmarking. Arch linux, latest 0.3.0 yazi.

**Comment by dedukun** [comment]
The issue was fixed in Yazi in PR https://github.com/sxyazi/yazi/pull/1467.

If people are using the stable release of Yazi, aka 0.3.0, you will need to wait for the next stable release, or alternative you can try [Yazi nightly](https://yazi-rs.github.io/docs/installation#official-binaries) or [install Yazi it with cargo](https://yazi-rs.github.io/docs/installation#cargo)

**Comment by panda7789** [comment]
Sorry for necroposting, but I was still wondering why bookmarks are not loaded from the .dds file. The format was correct, but then I noticed that in a newly generated one, there is a **newline at the end**. So, I added a newline to the end of my original .dds file, and voila, it works! 
Maybe someone will find this helpful. ❤️
