### ISSUE TITLE
Save last visited folder bookmark between yazi sessions

### ISSUE THREAD

**Issue by VimalMollyn** [dedukun/bookmarks.yazi#22]
Hi, thanks so much for helping out! Creating a new issue here to keep track of my comment from [this issue](https://github.com/dedukun/bookmarks.yazi/issues/10).

**Comment by dedukun** [comment]
Hey, thanks for creating the new issue.

I've created the PR #23 , can you do some tests to check if it is working as you expected?

Just a note but I changed the configurations, I've deprecated `save_last_directory` in favor of `last_directory`, so the `setup`  should look something like:

```lua
require("bookmarks"):setup({
	persist = "vim",
	last_directory = { enable = true, persist = true },
	desc_format = "full",
	notify = { enable = true },
})
```

**Comment by VimalMollyn** [comment]
This works perfectly, thank you so much!

**Comment by dedukun** [comment]
Thanks for testing, I'll merge it then.
