### ISSUE TITLE
Recommended bookmarks keymap overlaps with default linemode keymaps

### ISSUE THREAD

**Issue by ReedMerrill** [dedukun/bookmarks.yazi#25]
yazi version: 0.2.5

The recommended keymap for setting a bookmarkd ("m") overlaps with yazi's default linemode keymaps ("ms" to display file sizes, "mm" to display modified date-time, etc...), and it would be nice if this was noted in the README. I could do a PR that updates the README if you want.

**Comment by dedukun** [comment]
Hey,

Yes, If you could do a PR to update the README I would appreciate it.
