### ISSUE TITLE
plugin removes keybinding

### ISSUE THREAD

**Issue by TornaxO7** [dedukun/bookmarks.yazi#27]
Hello!
I have the following keymapping in my `keymap.toml`:
```toml
[manager]
keymap = [
     { on = [
    "d",
    "d",
  ], run = [
    "remove",
    "escape --visual --select",
  ], desc = "Move the files to the trash" },
]

prepend_keymap = [
  { on = [
    "m",
  ], run = "plugin bookmarks --args=save", desc = "Save current position as a bookmark" },
  { on = [
    "'",
  ], run = "plugin bookmarks --args=jump", desc = "Jump to a bookmark" },
  { on = [
    "b",
    "d",
  ], run = "plugin bookmarks --args=delete", desc = "Delete a bookmark" },
  { on = [
    "b",
    "d",
  ], run = "plugin bookmarks --args=delete", desc = "Delete a bookmark" },
]
```
but I'm not able to use `dd` in yazi. After commenting out
```
{ on = [
    "b",
    "d",
  ], run = "plugin bookmarks --args=delete", desc = "Delete a bookmark" },
```
I'm able to use `dd` again.

**Comment by dedukun** [comment]
Hey,

I copied your keymap.toml (with the keymaps for the bookmark uncommented) and I couldn't replicate the issue.

What version of Yazi are you using? Can you put here the output of `yazi --debug`?

**Comment by dedukun** [comment]
BTW you could also add the keymaps directly to the `manager` keymaps, without using `prepend_keymap`.

The `prepend_keymap` is more useful when you want to add new keymaps without changing the defaults, but seeing that you are already defining the full keymap you can just add this plugins keymaps there as well.

For more information you can check it here https://yazi-rs.github.io/docs/configuration/overview/#mixing.

**Comment by TornaxO7** [comment]
> Hey,
> 
> I copied your keymap.toml (with the keymaps for the bookmark uncommented) and I couldn't replicate the issue.
> 
> What version of Yazi are you using? Can you put here the output of `yazi --debug`?

Hm... that's weird. I'm using `Yazi 0.3.2 (69e7c8f 2024-08-30)`.
`yazi --debug`:

<details>

```

Yazi
    Version: 0.3.2 (69e7c8f 2024-08-30)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.2 (69e7c8f 2024-08-30)

Emulator
    Emulator.via_env: ("alacritty", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: X11

Desktop
    XDG_SESSION_TYPE           : Some("x11")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/run/current-system/sw/bin/fish")
    EDITOR             : Some("hx")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "$EDITOR $@", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "$EDITOR $@", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: None
    Zellij version     : 0.40.1

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-35
    fzf              : 0.54.2
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 1.14.2
    zoxide           : 0.9.4
    7z               : No such file or directory (os error 2)
    7zz              : 24.07
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/tornax/.local/state/yazi" directory.
```

</details>

> BTW you could also add the keymaps directly to the manager keymaps, without using prepend_keymap.
>
> The prepend_keymap is more useful when you want to add new keymaps without changing the defaults, but seeing that you are already defining the full keymap you can just add this plugins keymaps there as well.
>
> For more information you can check it here https://yazi-rs.github.io/docs/configuration/overview/#mixing.

Oh, that's good to know. Thank you!

I'll close this issue then for the time being. Maybe I'll find a way to reproduce this.
