### ISSUE TITLE
Bookmarks save location?

### ISSUE THREAD

**Issue by flexbusterman** [dedukun/bookmarks.yazi#28]
I can't figure out where the bookmarks data is saved and don't see any information regarding that in the documentation.

Would be nice to have access to the data for backups / dotfiles / synchronization.

Thank you for your work on this plugin!

**Comment by dedukun** [comment]
Hey,

This plugin is using [Yazi's DDS](https://yazi-rs.github.io/docs/dds) for saving the bookmarks, which saves its data on `~/.local/state/yazi/.dds` (in Windows it should be in something like `C:\Users\USERNAME\AppData\Roaming\yazi\state\.dds`).

This system however may be used by multiple plugins, so the file  might have more data  than just the data from the bookmarks.

**Comment by flexbusterman** [comment]
Ah, there it is : )
Thanks!
