### ISSUE TITLE
Micro plugin failed

### ISSUE THREAD

**Issue by euglevi** [dedukun/bookmarks.yazi#5]
I followed the readme instructions and I prepended the key to save a bookmark. However, when I press it, the task never completes and gives me this error message:

```
Micro plugin failed:
runtime error: [string "/home/eugenio/.cargo/registry/src/index.crate..."]:17: attempt to call a nil value (field 'sync')
stack traceback:
        [C]: in field 'sync'
        [string "/home/eugenio/.cargo/registry/src/index.crate..."]:17: in main chunk
```

Am I doing something wrong or is there a bug? I cannot easily debug this message given my null knowledge of rust. 

Thank you for the potentially very useful plugin! I really like the idea of not having to use tabs at all.

**Comment by Fuann-Kinoko** [comment]
It appears that [it](https://github.com/sxyazi/yazi/commit/dc1718fcf0d9b018a24aa71ef6a8a87d8f02ca6c) has not been included in the latest release. So you should build it manually, as stated in the README.

**Comment by dedukun** [comment]
It is as @Fuann-Kinoko said, the plugin uses `ya.sync` which is still not included in the latest release, so you must build from source.
If you have cargo you can install with `cargo install --locked --git https://github.com/sxyazi/yazi.git`

**Comment by euglevi** [comment]
Uh sorry about that, I did not realize that the latest branch was needed. Thank you for your support! We can close the issue.
