### ISSUE TITLE
Can I ask if the plugin data can't be persisted?

### ISSUE THREAD

**Issue by ListenV** [dedukun/bookmarks.yazi#6]
## 问题复现

保存书签后退出yazi，再次进入鸭子，丢失全部书签

## 环境

- Arch Linux
- yazi 0.2.4 (Arch Linux 2024-03-10)

**Comment by dedukun** [comment]
Hey, sorry I don't really know chinese, but no, at the moment the plugin doesn't support persistent bookmarks, however that's something that I want to add.

I'll have a look into it in the during the week.

**Comment by ListenV** [comment]
oh, sorry, my bad. I thought the author of this plugin was Chinese.

**Comment by dedukun** [comment]
This is a feature that I want to implement, so I'm reopening the issue so that if anyone else wants this, they can look for updates here.

**Comment by ListenV** [comment]
I have an idea, if yazi provides an API that doesn't have persistent storage, try using Lua's tool library to implement persistent storage.

For example: you can store bookmark data to a Json file.

**Comment by dedukun** [comment]
Yeah, I don't think there's a standard way to do this in Yazi (I'm asking it in the discord at the moment), so I think that we need to do this directly in Lua.

**Comment by dedukun** [comment]
Just an update, I didn't forgot about this feature, I'm just waiting for https://github.com/sxyazi/yazi/pull/826 because it seems that it will help us implement the persistence that we want.

**Comment by go0d1uck** [comment]
Let me try it! Thanks for your work.

**Comment by ListenV** [comment]
Awesome!
