### ISSUE TITLE
99%, 1 left | bookmarks won't save

### ISSUE THREAD

**Issue by pepperonipizzah** [dedukun/bookmarks.yazi#9]
![image](https://github.com/dedukun/bookmarks.yazi/assets/76881322/eb24cf01-1a02-4491-8f1e-558526a4e7e1)

I can assign bookmarks and use them with m and ' respectively but does not persist when i close and reopen yazi. Whenever i press "m" it just says `99%, 1 left`.

Any ideas?

**Comment by dedukun** [comment]
Hey, at the moment the bookmarks don't persist, that's something that I want to add but I'm waiting for a PR from Yazi to be merged before looking into it. That feature is being tracked in #6 .

As for the `99%, 1 left` when you press `m`, that's the normal behavior of the function [`ya.which`](https://yazi-rs.github.io/docs/plugins/utils/#ya.which)  which we use in the plugin, it just means that the plugin is waiting for an input from the user.

**Comment by BigLadDylan** [comment]
i was imagining something like ranger's bookmarks. i did not know that bookmarks weren't able to persist beyond sessions. 

If theres any update i would appreciate you letting me know because this feature is quite crucial to my productivity.

**Comment by BigLadDylan** [comment]
Thanks.

**Comment by BigLadDylan** [comment]
idk how to alter it but if you press g, there are some hardcoded "bookmarks" 

is it possible to alter them?

**Comment by BigLadDylan** [comment]
well it is if you edit keymap.toml,

I suppose thats a temporary workaround to bookmarks?

**Comment by dedukun** [comment]
`keymap.toml` is the official way to add keybindings in Yazi, such as a keybinding to go to a directory.

This plugin exist to allow the user to dynamically add bookmark's in a vim-like way, however if your use case is to have a permanent binding to go to a specific folder, you should add that to `keymap.toml`.

**Comment by dedukun** [comment]
Hey I'm closing this issue in favor of #6 for the persistence question. 
I'm only waiting for a fix in upstream Yazi but PR #14 is ready, so I think that this feature will be merged soon.
